---


dist: 'xenial'

language: 'python'

python:
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10-dev'

jobs:
  allow_failures:
    - python: '3.10-dev'
  fast_finish: true

install:
  - 'python3 -m pip install tox tox-travis'

script:
  - 'python3 -m tox'
  - 'python3 -m tox -e package'

deploy:
  - provider: 'releases'
    api_key: '${GITHUB_TOKEN}'
    file_glob: true
    file: 'dist/*'
    skip_cleanup: true
    on:
      python: '3.9'
      tags: true
  - provider: 'pypi'
    distributions: 'sdist bdist_wheel'
    user: '${PYPI_USER}'
    password: '${PYPI_PASSWORD}'
    on:
      python: '3.9'
      tags: true

sudo: false


... EOF
